// Curated word packs. Each pack has Easy / Medium / Hard tiers so room hosts
// can tune difficulty, and a custom pack can be supplied by the host at
// runtime (see room.customWords in roomManager.js).
//
// Classic has been replaced with the expanded child/modesty-safe Pictionary
// bank classified into Easy / Medium / Hard tiers.

export const WORD_PACKS = {
  Classic: {
    Easy: [
      "Dog", "Cat", "Elephant", "Giraffe", "Lion", "Tiger", "Zebra", "Monkey",
      "Gorilla", "Kangaroo", "Koala", "Panda", "Penguin", "Dolphin", "Whale", "Shark",
      "Octopus", "Seahorse", "Crab", "Lobster", "Starfish", "Turtle", "Frog", "Toad",
      "Snake", "Lizard", "Owl", "Eagle", "Hawk", "Parrot", "Peacock", "Swan",
      "Duck", "Goose", "Chicken", "Rooster", "Turkey", "Pigeon", "Sparrow", "Bat",
      "Mouse", "Rat", "Squirrel", "Rabbit", "Hamster", "Fox", "Wolf", "Bear",
      "Deer", "Moose", "Elk", "Reindeer", "Horse", "Pony", "Donkey", "Mule",
      "Cow", "Bull", "Calf", "Sheep", "Lamb", "Goat", "Pig", "Piglet",
      "Camel", "Llama", "Alpaca", "Rhino", "Hippo", "Cheetah", "Leopard", "Jaguar",
      "Panther", "Lynx", "Jackal", "Sloth", "Anteater", "Dingo", "Seal", "Eel",
      "Catfish", "Goldfish", "Koi Fish", "Salmon", "Tuna", "Trout", "Bass", "Coral",
      "Butterfly", "Caterpillar", "Moth", "Bee", "Wasp", "Ant", "Spider", "Grasshopper",
      "Cricket", "Ladybug", "Beetle", "Firefly", "Dragonfly", "Mosquito", "Fly", "Snail",
      "Slug", "Worm", "Earthworm", "Mantis", "Termite", "Mussel", "Clam", "Oyster",
      "Squid", "Gecko", "Newt", "Tortoise", "Crane", "Stork", "Pelican", "Seagull",
      "Crow", "Raven", "Magpie", "Robin", "Cardinal", "Toucan", "Macaw", "Cockatoo",
      "Canary", "Finch", "Heron", "Quail", "Emu", "Unicorn", "Dragon", "Puppy",
      "Kitten", "Duckling", "Chick", "Foal", "Fawn", "Cub", "Joey", "Tadpole",
      "Tapir", "Badger", "Weasel", "Ferret", "Gerbil", "Bird Nest", "Pizza", "Hamburger",
      "Hot Dog", "Sandwich", "Taco", "Burrito", "Sushi", "Spaghetti", "Lasagna", "Pancake",
      "Waffle", "Omelette", "Bacon", "Sausage", "Steak", "Ribs", "Meatball", "Dumpling",
      "Fries", "Nachos", "Popcorn", "Pretzel", "Bagel", "Croissant", "Donut", "Muffin",
      "Cupcake", "Cake", "Cheesecake", "Brownie", "Cookie", "Pie", "Apple Pie", "Pumpkin Pie",
      "Ice Cream", "Sundae", "Milkshake", "Smoothie", "Popsicle", "Yogurt", "Pudding", "Chocolate Bar",
      "Candy Cane", "Lollipop", "Gummy Bear", "Caramel", "Jellybean", "Cotton Candy", "Peanut Butter", "Jam Jar",
      "Butter", "Cheese", "Egg", "Milk", "Cereal", "Oatmeal", "Toast", "Bread",
      "Baguette", "Pasta", "Ramen", "Noodles", "Rice", "Fried Rice", "Curry", "Soup",
      "Stew", "Chili", "Salad", "Coleslaw", "Wrap", "Calzone", "Apple", "Banana",
      "Orange", "Grape", "Strawberry", "Blueberry", "Raspberry", "Watermelon", "Pineapple", "Mango",
      "Peach", "Pear", "Cherry", "Lemon", "Lime", "Coconut", "Avocado", "Fig",
      "Carrot", "Potato", "Tomato", "Onion", "Garlic", "Broccoli", "Cauliflower", "Corn",
      "Cucumber", "Pepper", "Pumpkin", "Mushroom", "Lettuce", "Cabbage", "Spinach", "Celery",
      "Eggplant", "Beet", "Radish", "Peas", "Green Beans", "Sweet Potato", "Ginger", "Chili Pepper",
      "Olive", "Pickle", "Coffee", "Tea", "Hot Chocolate", "Lemonade", "Orange Juice", "Soda Can",
      "Water Bottle", "Juice Box", "Teapot", "Coffee Pot", "Kettle", "Mug", "Straw", "Honey Jar",
      "Ketchup", "Mustard", "Mayonnaise", "Salt Shaker", "Pepper Shaker", "Sugar Cube", "Flour Bag", "Vanilla",
      "Birthday Candle", "Picnic Basket", "Lunch Box", "Bento Box", "Grocery Bag", "Apron", "Chef Hat", "Biryani",
      "Samosa", "Kebab", "Naan", "Chai", "Taco Truck", "Burger", "Bakery", "Cafe",
      "Food Truck", "Ice Truck", "Soccer Ball", "Basketball", "Football", "Baseball", "Tennis Ball", "Golf Ball",
      "Volleyball", "Rugby Ball", "Cricket Bat", "Hockey Stick", "Ping Pong", "Bowling Ball", "Bowling Pin", "Pool Table",
      "Billiards", "Chess Board", "Checkers", "Dominoes", "Playing Cards", "Dice", "Puzzle", "Yo-Yo",
      "Kite", "Frisbee", "Skateboard", "Surfboard", "Snowboard", "Ski", "Sled", "Helmet",
      "Baseball Glove", "Baseball Bat", "Tennis Racket", "Golf Club", "Soccer Goal", "Basketball Hoop", "Jump Rope", "Punching Bag",
      "Boxing Gloves", "Wrestling Mat", "Yoga Mat", "Dumbbell", "Barbell", "Medal", "Trophy", "Whistle",
      "Stadium", "Finish Line", "Running Track", "Swimming Pool", "Diving Board", "Swim Goggles", "Life Vest", "Rowing Boat",
      "Kayak", "Canoe", "Paddle", "Bow", "Arrow", "Fishing Rod", "Fishing Reel", "Hockey Puck",
      "Game Controller", "Joystick", "Board Game", "Sudoku", "Sports Cap", "Baseball Cap", "Goalie Gloves", "Running Shoes",
      "Ski Boots", "Roller Skates", "Javelin", "Discus", "Hurdle", "Podium", "Sun", "Moon",
      "Star", "Cloud", "Rainbow", "Lightning", "Thunderstorm", "Tornado", "Hurricane", "Snowflake",
      "Snowman", "Raindrop", "Wind", "Fog", "Mist", "Sunrise", "Sunset", "Eclipse",
      "Comet", "Shooting Star", "Planet", "Saturn", "Galaxy", "Volcano", "Earthquake", "Wave",
      "Ocean", "River", "Lake", "Waterfall", "Stream", "Pond", "Desert", "Sand Dune",
      "Oasis", "Cactus", "Palm Tree", "Forest", "Jungle", "Rainforest", "Mountain", "Valley",
      "Canyon", "Cliff", "Cave", "Island", "Beach", "Seashell", "Glacier", "Iceberg",
      "Meadow", "Swamp", "Marsh", "Coral Reef", "Tide Pool", "Tree", "Oak Tree", "Pine Tree",
      "Willow Tree", "Bamboo", "Flower", "Rose", "Sunflower", "Tulip", "Daisy", "Lily",
      "Orchid", "Cherry Blossom", "Dandelion", "Clover", "Leaf", "Autumn Leaves", "Pine Cone", "Acorn",
      "Grass", "Bush", "Vine", "Root", "Seed", "Rock", "Boulder", "Pebble",
      "Crystal", "Gemstone", "Diamond", "Gold Nugget", "Lava", "Fire", "Campfire", "Smoke",
      "Ash", "Mud", "Puddle", "Frost", "Icicle", "Hail", "Blizzard", "Spider Web",
      "Ant Hill", "Beehive", "Chair", "Table", "Sofa", "Bed", "Pillow", "Blanket",
      "Lamp", "Light Bulb", "Candle", "Mirror", "Clock", "Alarm Clock", "Wristwatch", "Calendar",
      "Picture Frame", "Painting", "Vase", "Flower Pot", "Rug", "Curtain", "Window", "Door",
      "Key", "Keyhole", "Doorbell", "Staircase", "Ladder", "Fan", "Heater", "Fireplace",
      "Chimney", "Umbrella", "Raincoat", "Boots", "Gloves", "Scarf", "Hat", "Cap",
      "Backpack", "Suitcase", "Purse", "Wallet", "Glasses", "Sunglasses", "Necklace", "Ring",
      "Bracelet", "Earrings", "Crown", "Tiara", "Flashlight", "Lantern", "Matchstick", "Scissors",
      "Needle", "Thread", "Button", "Zipper", "Sewing Machine", "Broom", "Mop", "Bucket",
      "Sponge", "Soap", "Toothbrush", "Toothpaste", "Towel", "Bathtub", "Shower", "Sink",
      "Toilet", "Faucet", "Comb", "Hairbrush", "Hair Dryer", "Razor", "Perfume", "Fridge",
      "Stove", "Oven", "Microwave", "Toaster", "Blender", "Dishwasher", "Washing Machine", "Dryer",
      "Vacuum", "Iron", "Hanger", "Closet", "Drawer", "Shelf", "Bookshelf", "Cupboard",
      "Trash Can", "Recycling Bin", "Wrench", "Hammer", "Screwdriver", "Nail", "Saw", "Drill",
      "Tool Box", "Measuring Tape", "Paint Brush", "Paint Can", "Ruler", "Stapler", "Tape", "Glue Stick",
      "Envelope", "Stamp", "Mailbox", "Newspaper", "Book", "Notebook", "Pencil", "Pen",
      "Eraser", "Highlighter", "Crayon", "Marker", "Chalk", "Chalkboard", "Whiteboard", "Globe",
      "Magnifying Glass", "Compass", "Map", "Passport", "Ticket", "Camera", "Photograph", "Television",
      "Remote", "Radio", "Headphones", "Speaker", "Microphone", "Telephone", "Smartphone", "Laptop",
      "Computer Mouse", "Keyboard", "Printer", "Battery", "Laundry Basket", "Yarn Ball", "Quilt", "Throw Pillow",
      "Window Blinds", "Shower Curtain", "Bath Mat", "Tissue Box", "Paper Towel", "Dustpan", "Rubber Gloves", "Shoe Rack",
      "Coat Rack", "Welcome Mat", "Garage Door", "Driveway", "Garden Gate", "Patio Chair", "Beach Umbrella", "Beach Chair",
      "Beach Towel", "Camping Tent", "Sleeping Bag", "Lantern Light", "Cooler Box", "Floor Lamp", "Desk Lamp", "Night Light",
      "Bunk Bed", "Crib", "Rocking Chair", "Bean Bag", "Coffee Table", "Dining Table", "Spice Rack", "Dish Rack",
      "Drying Rack", "Key Hook", "Towel Rack", "Pliers", "Wrench Set", "Step Stool", "Car", "Truck",
      "Bus", "Bicycle", "Motorcycle", "Scooter", "Train", "Subway", "Tram", "Airplane",
      "Helicopter", "Rocket", "Spaceship", "Satellite", "Boat", "Sailboat", "Yacht", "Submarine",
      "Speedboat", "Ferry", "Fire Truck", "Police Car", "Taxi", "Tractor", "Bulldozer", "Forklift",
      "Golf Cart", "Race Car", "Monster Truck", "Garbage Truck", "School Bus", "Cable Car", "Wagon", "Carriage",
      "Unicycle", "Tricycle", "Traffic Light", "Stop Sign", "Road", "Highway", "Bridge", "Tunnel",
      "Parking Lot", "Gas Station", "Steering Wheel", "Tire", "License Plate", "Seatbelt", "Gas Pump", "Airport",
      "Runway", "Train Station", "Bus Stop", "Space Shuttle", "Delivery Van", "Mail Truck", "Camper Van", "Tow Truck",
      "Dump Truck", "Fire Hydrant", "Crosswalk", "Car Wash", "Baggage Cart", "Train Tracks", "Taxi Stand", "Doctor",
      "Nurse", "Dentist", "Surgeon", "Vet", "Teacher", "Professor", "Student", "Scientist",
      "Astronaut", "Pilot", "Flight Attendant", "Firefighter", "Police Officer", "Detective", "Lawyer", "Judge",
      "Banker", "Accountant", "Chef", "Baker", "Waiter", "Waitress", "Barista", "Farmer",
      "Fisherman", "Carpenter", "Electrician", "Plumber", "Mechanic", "Architect", "Engineer", "Construction Worker",
      "Painter", "Artist", "Musician", "Singer", "Dancer", "Actor", "Actress", "Photographer",
      "Writer", "Journalist", "Athlete", "Coach", "Soldier", "Sailor", "Knight", "King",
      "Queen", "Prince", "Princess", "Wizard", "Witch", "Superhero", "Villain", "Ninja",
      "Pirate", "Cowboy", "Clown", "Magician", "Mime", "Barber", "Hairdresser", "Tailor",
      "Jeweler", "Librarian", "Postman", "Lifeguard", "Tour Guide", "Grandfather", "Grandmother", "Father",
      "Mother", "Baby", "Toddler", "Twins", "Bride", "Groom", "Monk", "Priest",
      "Comedian", "Poet", "Sculptor", "Inventor", "Explorer", "Zookeeper", "Park Ranger", "Security Guard",
      "Crossing Guard", "Realtor", "Train Conductor", "Ship Captain", "Mail Carrier", "Delivery Person", "Superman", "Batman",
      "Spiderman", "Ironman", "Hulk", "Thor", "Santa Claus", "Easter Bunny", "Tooth Fairy", "Cinderella",
      "Snow White", "Sleeping Beauty", "Little Mermaid", "Peter Pan", "Tinker Bell", "Pinocchio", "Mad Hatter", "Scarecrow",
      "Tin Man", "Mummy", "Ghost", "Skeleton", "Viking", "Samurai", "Genie", "Aladdin",
      "Sinbad", "Sphinx", "Bigfoot", "King Kong", "Godzilla", "Zeus", "Hercules", "Angel",
      "Dead Sea", "Atlantis", "Castle", "Windmill", "Lighthouse", "Barn", "Log Cabin", "Igloo",
      "Treehouse", "Skyscraper", "Downtown Street", "Village Square", "National Park", "Zoo", "Aquarium", "Museum",
      "Library", "School", "University", "Hospital", "Church", "Mosque", "Temple", "Fortress",
      "K2 Peak", "Hunza Valley", "Eye", "Nose", "Mouth", "Ear", "Tooth", "Tongue",
      "Hand", "Finger", "Thumb", "Fist", "Arm", "Elbow", "Shoulder", "Leg",
      "Knee", "Foot", "Toe", "Heart", "Brain", "Lung", "Skull", "Spine",
      "Muscle", "X-Ray", "Thermometer", "Bandage", "Crutches", "Wheelchair", "Cast", "Syringe",
      "Pill Bottle", "Medkit", "Band Aid", "Ice Pack", "Heating Pad", "Hospital Bed", "Graduation Cap", "Diploma",
      "Report Card", "Test Paper", "Pencil Case", "Calculator", "World Map", "Beaker", "Test Tube", "Lab Coat",
      "School Desk", "Locker", "Gym Class", "Library Card", "Office Desk", "Office Chair", "Paper Clip", "Sticky Note",
      "Conference Table", "Cubicle", "Business Card", "Planner", "To-Do List", "Bar Graph", "Guitar", "Electric Guitar",
      "Bass Guitar", "Piano", "Violin", "Cello", "Drum Set", "Drumstick", "Trumpet", "Saxophone",
      "Flute", "Clarinet", "Harmonica", "Accordion", "Harp", "Tambourine", "Maracas", "Xylophone",
      "Triangle", "Music Note", "Sheet Music", "Baton", "Music Stand", "Gong", "Cymbal", "Paintbrush",
      "Easel", "Palette", "Canvas", "Sculpture", "Pottery Wheel", "Clay Pot", "Origami Crane", "Puppet",
      "Mask", "Theater Curtain", "Film Camera", "Film Reel", "Art Gallery", "Christmas Tree", "Stocking", "Santa Sleigh",
      "Gingerbread House", "Ornament", "Wreath", "Present", "Gift Bow", "Costume", "Witch Hat", "Candy Bowl",
      "Easter Egg", "Easter Basket", "Pilgrim Hat", "Fireworks", "Confetti", "Party Hat", "Balloon", "Wedding Ring",
      "Anniversary Card", "National Flag", "Menorah", "Diwali Lamp", "Running", "Jumping", "Swimming", "Flying",
      "Dancing", "Singing", "Laughing", "Crying", "Sleeping", "Eating", "Drinking", "Cooking",
      "Baking", "Cleaning", "Drawing", "Writing", "Reading", "Typing", "Climbing", "Falling",
      "Skipping", "Hopping", "Crawling", "Walking", "Skating", "Skiing", "Surfing", "Diving",
      "Throwing", "Catching", "Kicking", "Punching", "Hugging", "Waving", "Clapping", "Pointing",
      "Whispering", "Shouting", "Sneezing", "Yawning", "Stretching", "Exercising", "Pushing", "Pulling",
      "Carrying", "Balancing", "Juggling", "Praying", "Fishing", "Camping", "Hiking", "Gardening",
      "Building", "Digging", "Sawing", "Hammering", "Sewing", "Knitting", "Driving", "Riding Bike",
      "Riding Horse", "Brushing Teeth", "Washing Hands", "Making Bed", "Folding Laundry", "Ironing", "Sweeping", "Mopping",
      "Watering Plants", "Mowing Lawn", "Raking Leaves", "Shoveling Snow", "Flying Kite", "Opening Presents", "Wrapping Gifts", "Taking Photo",
      "Shaking Hands", "High Five", "Fist Bump", "Sliding", "Swinging", "Seesaw", "Riding Scooter", "Horseback Riding",
      "Spring", "Summer", "Autumn", "Winter", "Sunny Day", "Rainy Day", "Snowy Day", "Windy Day",
      "Cloudy Day", "Midnight", "Calendar Page", "New Year", "Decade", "Century", "Alien", "Ufo",
      "Astronaut Helmet", "Space Suit", "Mars Rover", "Space Station", "Asteroid", "Solar System", "Jupiter", "Mars Planet",
      "Robot", "Time Machine", "Magic Wand", "Spell Book", "Dragon Egg", "Fairy Wings", "Unicorn Horn", "Mermaid Tail",
      "Treasure Chest", "Pirate Ship", "Pirate Flag", "Treasure Map", "Message Bottle", "Desert Island", "Bubble Wand", "Pinwheel",
      "Spinning Top", "Marbles", "Teddy Bear", "Doll", "Building Blocks", "Toy Train", "Toy Car", "Action Figure",
      "Stuffed Animal", "Rocking Horse", "Wooden Puzzle", "Paper Airplane", "Sticker Sheet", "Coloring Book", "Piggy Bank", "Coin Stack",
      "Dollar Bill", "Credit Card", "Cash Register", "Shopping Bag", "Price Tag", "Gift Card", "Receipt", "Charger Cable",
      "Power Outlet", "Traffic Cone", "Caution Tape", "Smoke Detector", "Security Camera", "Padlock", "Rope Coil", "Fishing Net",
      "Birdcage", "Fish Tank", "Hamster Wheel", "Leash", "Collar", "Pet Bed", "Litter Box", "Bird Feeder",
      "Dog House", "Cat Tree", "Fish Bowl", "Terrarium", "Weather Vane", "Sundial", "Wind Chime", "Bird Bath",
      "Flower Bed", "Watering Can", "Garden Hose", "Lawn Mower", "Rake", "Shovel", "Pitchfork", "Hay Bale",
      "Barn Door", "Silo", "Snow Globe", "Music Box", "Jewelry Box", "Treasure Box", "Lunchbox", "Toolbox",
      "Sewing Box", "Birdhouse", "Dollhouse", "Sandbox", "Playground Slide", "Swing Set", "Monkey Bars", "Merry-Go-Round",
      "Bumper Cars", "Water Slide", "Go-Kart", "Mini Golf", "Arcade Tokens", "Claw Machine", "Photo Booth", "Balloon Animal",
      "Face Paint", "Clown Nose", "Circus Tent", "Ring Toss", "Monarch Butterfly", "Silkworm", "Cobra", "Python",
      "Viper", "Box Turtle", "Snapping Turtle", "Skink", "T-Shirt", "Dress Shirt", "Sweater", "Hoodie",
      "Jacket", "Coat", "Blazer", "Tuxedo", "Skirt", "Shorts", "Jeans", "Trousers",
      "Pajamas", "Mittens", "Beanie", "Cowboy Hat", "Top Hat", "Headband", "Bow Tie", "Necktie",
      "Belt", "Sneakers", "Sandals", "Slippers", "Socks", "Veil", "Brooch", "Moat",
      "Apartment", "Office Tower", "Shopping Mall", "Grocery Store", "Gazebo", "Fire Station", "Police Station", "City Hall",
      "Post Office", "Bank", "Tablet", "Drone", "Game Console", "Webcam", "Solar Panel", "Wind Turbine",
      "Smart Bulb", "Doorbell Camera", "Atm Machine", "Self Checkout", "Cell Tower", "Server Rack", "Hard Drive", "Equator Line",
      "Savanna", "Fjord", "Plateau", "Mesa", "Happy Face", "Sad Face", "Angry Face", "Love Heart",
      "Broken Heart", "Thumbs Up", "Thumbs Down", "Peace Sign", "Ok Sign", "Detour Sign", "Danger Sign", "Exit Sign",
      "Peace Dove", "Olive Branch", "Kimono", "Sari", "Kilt", "Maypole", "Bagpiper", "Mariachi",
      "Nesting Doll", "Birthday Hat", "Goodie Bag", "Pacifier", "Baby Bottle", "Stroller", "High Chair", "Baby Monitor",
      "Hayride", "Sledding", "Beach Ball", "Comic Book", "Encyclopedia", "Dictionary", "Atlas", "Cookbook",
      "Textbook", "Rapids", "Wind Farm", "Solar Farm", "Power Plant", "Water Tower", "Factory Worker", "Baseball Field",
      "Tennis Court", "Golf Course", "Soccer Field", "Running Shoe", "Gym Bag", "Sports Bag", "Energy Bar", "Victory Lap",
      "Blue Ribbon", "Trophy Case", "Press Box", "Parking Garage", "Bike Rack", "Training Wheels", "Bike Chain", "Bike Pedal",
      "Bike Basket", "Car Hood", "Car Trunk", "Car Bumper", "Car Mirror", "Car Wiper", "Car Horn", "Car Battery",
      "Spare Tire", "Tow Rope", "Muffler", "Gas Tank", "Fuel Gauge", "Glove Box", "Brake Pedal", "Gas Pedal",
      "Turn Signal", "Wiper Blade", "Oil Can", "Bicycle Bell", "Bike Lane", "Crosswalk Sign", "Kitchen Sink", "Kitchen Counter",
      "Dining Chair", "Dining Set", "Table Cloth", "Place Mat", "Napkin Ring", "Serving Tray", "Serving Spoon", "Ladle",
      "Tongs", "Whisk Tool", "Grater", "Peeler", "Can Opener", "Bottle Opener", "Colander", "Strainer",
      "Sieve", "Funnel", "Rolling Pin", "Pastry Brush", "Cookie Cutter", "Cake Stand", "Cake Pan", "Muffin Tin",
      "Baking Sheet", "Mixing Bowls", "Measuring Spoon", "Oven Mitts", "Pot Holder", "Trivet", "Dish Towel", "Tea Towel",
      "Fork Set", "Spoon Set", "Sushi Mat", "Soy Sauce", "Wasabi", "Noodle Bowl", "Wok Pan", "Rice Cooker",
      "Slow Cooker", "Air Fryer", "Coffee Grinder", "Tea Bag", "Tea Kettle", "Ice Tray", "Soda Bottle", "Juice Pitcher",
      "Water Pitcher", "Milk Jug", "Sugar Bowl", "Butter Dish", "Fruit Bowl", "Bread Box", "Cookie Jar", "Candy Jar",
      "Spice Jars", "Pantry Door", "Fridge Door", "Ice Maker", "Fridge Magnet", "Stove Knob", "Oven Door", "Oven Rack",
      "Stovetop", "Office Building", "Office Window", "Office Plant", "Office Printer", "Office Phone", "Office Lamp", "Office Clock",
      "Office Calendar", "Office Folder", "File Folder", "Binder", "Whiteboard Eraser", "Bulletin Board", "Push Pin", "Rubber Band",
      "Binder Clip", "Label Maker", "Name Tag", "Id Badge", "Lanyard", "Laptop Bag", "Laptop Charger", "Mouse Pad",
      "Monitor Screen", "Headset", "Projector", "Markers Set", "Highlighter Set", "Notebook Spiral", "Notepad", "Index Card",
      "Card Holder", "Desk Organizer", "Pencil Holder", "Tape Dispenser", "Letter Opener", "Envelope Stack", "Rubber Stamp", "Water Cooler",
      "Coffee Maker", "Break Room", "Meeting Room", "Boardroom Table", "Glass Door", "Waiting Chair", "Elevator", "Revolving Door",
      "Fire Exit", "Exit Door", "Handrail", "Floor Sign", "Wet Floor", "Caution Cone", "Garden Shed", "Garden Fence",
      "Garden Path", "Garden Bench", "Garden Statue", "Garden Fountain", "Garden Pond", "Flower Bouquet", "Flower Crown", "Potted Plant",
      "Hanging Basket", "Window Box", "Planter Box", "Seed Packet", "Hose Reel", "Garden Fork", "Hand Trowel", "Compost Bin",
      "Greenhouse Door", "Vegetable Garden", "Herb Garden", "Rose Bush", "Topiary", "Bonsai Tree", "Moss Patch", "Lily Pad",
      "Cattail", "Bulrush", "Maple Leaf", "Oak Leaf", "Palm Leaf", "Fern Leaf", "Cactus Flower", "Succulent",
      "Bamboo Stalk", "Tree Stump", "Tree Branch", "Tree Trunk", "Tree Bark", "Tree Roots", "Forest Floor", "Fallen Log",
      "Mushroom Patch", "Fairy Ring", "Woodland Path", "Hiking Trail", "Trail Sign", "Camp Stove", "Camp Chair", "Camp Table",
      "Camp Lantern", "Fire Pit", "Camp Axe", "Rope Ladder", "Climbing Rope", "Tent Pole", "Tent Stake", "Tarp",
      "Water Filter", "Trail Mix", "Map Case", "Gps Watch", "Headlamp", "Emergency Blanket", "Life Jacket", "Paddle Board",
      "Art Studio", "Sketch Pad", "Sketchbook", "Drawing Pencil", "Charcoal Stick", "Pastel Set", "Watercolor Set", "Paint Palette",
      "Paint Roller", "Paint Tray", "Spray Paint", "Airbrush", "Stencil", "Glitter Jar", "Felt Fabric", "Fabric Scissors",
      "Yarn Skein", "Crochet Hook", "Knitting Kit", "Bead Box", "Bead String", "Charm Bracelet", "Friendship Bracelet", "Pottery Clay",
      "Sculpting Tool", "Wood Carving", "Stone Carving", "Sand Art", "Mosaic Tile", "Stained Glass", "Loom", "Fountain Pen",
      "Ink Bottle", "Quill Pen", "Scroll", "Old Map", "Open Chest", "Antique Clock", "Antique Vase", "Antique Mirror",
      "Vintage Camera", "Vintage Radio", "Record Player", "Photo Album", "Scrapbook", "Postcard", "Greeting Card", "Birthday Card",
      "Thank-You Card", "Invitation Card", "Gift Wrap", "Gift Tag", "Gift Box", "Shopping Basket", "Reusable Bag", "Tote Bag",
      "Drawstring Bag", "Duffel Bag", "Messenger Bag", "Snow Tube", "Ice Rink", "Hockey Goal", "Bobsled", "Luge",
      "Ski Jump", "Ski Pole", "Lift Chair", "Snowmobile", "Frozen Lake", "Frozen Pond", "Fishing Hole", "Coat Hood",
      "Ear Muffs", "Hand Warmer", "Snow Boots", "Snow Shovel", "Snow Blower", "Ice Scraper", "Window Frost", "Steam Breath",
      "Hot Tub", "Sauna", "Wood Stove", "Wood Pile", "Firewood Log", "Fire Poker", "Matchbox", "Lighter",
      "Candle Holder", "Candle Wax", "Incense Stick", "Oil Lamp", "Gas Lamp", "Street Lamp", "Lamp Post", "Road Cone",
      "Road Barrier", "Construction Barrier", "Road Roller", "Jackhammer", "Cement Mixer", "Bulldozer Blade", "Excavator", "Backhoe",
      "Truck Bed", "Hard Hat", "Safety Vest", "Safety Goggles", "Work Gloves", "Steel Boots", "Tool Belt", "Chalk Line",
      "Spirit Level", "Square Tool", "Clamp Tool", "Allen Key", "Screw Set", "Nail Box", "Putty Knife", "Sandpaper",
      "Sanding Block", "Wood Glue", "Wood Plank", "Plywood Sheet", "Lumber Stack", "Nail Board", "Tool Shed", "Theater Stage",
      "Theater Seats", "Tree Line", "Tide Line", "Inlet", "Cove", "Plaza", "Pier", "Jetty",
      "Marina", "Factory", "Sawmill", "Workshop", "Tomb", "Monument", "Dome", "Chapel",
      "Shrine", "Pagoda", "Stupa", "Abbey", "Convent", "Footpath", "Sidewalk", "Street Sign",
      "Alley", "Lane", "Avenue", "Drawbridge Road", "Power Line", "Motel Sign", "Diner", "Pharmacy Sign",
      "Clinic Sign", "Dentist Chair", "Salon Chair", "Boxing Ring", "Aviary", "Classroom Door", "Paddock", "Archway",
      "Balcony", "Railing", "Terrace", "Veranda", "Patio", "Hallway", "Corridor", "Skylight",
      "Dormer Window", "Bay Window", "Arched Window", "Shutter", "Screen Door", "Sliding Door", "French Door", "Banister",
      "Column", "Pillar", "Portico", "Gable", "Eaves", "Cornice", "Paved Road", "Pergola",
      "Neon Sign", "Marquee Sign", "Shop Window", "Ticket Window", "Soup Bowl", "Salad Bowl", "Dinner Plate", "Side Plate",
      "Saucer", "Tea Cup", "Coffee Cup", "Goblet", "Pitcher", "Thermos", "Food Jar", "Serving Cart",
      "Coaster", "Tandoor", "Oil Bottle", "Vinegar Bottle", "Shampoo Bottle", "Conditioner Bottle", "Lotion Bottle", "Measuring Cup",
      "Shoe Brush", "Door Mat", "Dresser", "Makeup Table", "Ring Box", "Watch Box", "Hat Box", "Cardboard Box",
      "Parcel", "Desk Bell", "Name Plate", "Inkwell", "Magazine Rack", "Book Cart", "Bookmark", "Magnifier Lamp",
      "Hammock", "Folding Chair", "Folding Table", "Picnic Blanket", "Cooler Bag", "Travel Pillow", "Canteen Cup", "Sawhorse",
      "Pegboard", "Tool Rack", "Dog Bowl", "Cat Bowl", "Saddle Blanket", "Cowbell", "Electric Blanket", "Fuse Box",
      "Padlock Key", "Safe Box", "Cash Box", "Cheque Book", "Bank Card", "Id Card", "Membership Card", "Access Card",
      "Metro Card", "Coupon", "Voucher", "Shopping Cart", "Baobab Tree", "Redwood Tree", "Sequoia", "Birch Tree",
      "Maple Tree", "Cedar Tree", "Cypress Tree", "Spruce Tree", "Fir Tree", "Olive Tree", "Banana Tree", "Mango Tree",
      "Apple Tree", "Orange Tree", "Lemon Tree", "Lavender", "Jasmine Flower", "Hibiscus", "Lotus Flower", "Poppy Flower",
      "Bluebell", "Marigold", "Lichen", "Seaweed", "Mushroom Cap", "Tree Ring", "Seedling", "Sprout",
      "Hedge", "Orchard Tree", "Mackerel", "Sardine", "Anchovy", "Cod Fish", "Herring", "Lionfish",
      "Betta Fish", "Guppy", "Tropical Fish", "Swan Boat", "Cicada", "Walking Stick", "Moonbeam", "Atom",
      "Molecule", "Flask", "Magnet", "Prism", "Pluto", "Uranus", "Neptune", "Abacus",
      "Number Line", "Fraction Pie", "Geometry Set", "Times Table", "School Bell", "Answer Key", "Reading Lamp", "Poetry Book",
      "History Book", "Map Book", "Language Book", "Music Book", "Art Book", "Papyrus", "Ancient Coin", "Roman Coin",
      "Offering Bowl", "Temple Bell", "Church Bell", "Ankh", "Longship", "Teepee", "Yurt", "Mosaic Lamp",
      "Seal Ring", "Archaeology Brush", "Shawarma", "Falafel", "Hummus Bowl", "Tahini Jar", "Kabsa", "Kunafa",
      "Baklava", "Dolma", "Koshari", "Tagine", "Couscous", "Injera", "Arepa", "Empanada",
      "Tamale", "Churros", "Mochi", "Onigiri", "Tempura", "Udon Bowl", "Pho Bowl", "Laksa",
      "Moon Cake", "Kimchi Jar", "Bibimbap Bowl", "Dosa", "Idli Plate", "Vada", "Paratha", "Roti",
      "Chapati", "Puri", "Pakora", "Chaat Bowl", "Nihari", "Haleem", "Karahi", "Kheer Bowl",
      "Rasmalai", "Barfi", "Laddu", "Kulfi", "Paan Leaf", "Achar Jar", "Shepherds Pie", "Paella",
      "Risotto", "Gnocchi", "Crepe", "Macaron", "Pierogi", "Borscht", "Blini", "Slushie",
      "Espresso Cup", "Cricket Ball", "Score Card", "Squash Ball", "Home Plate", "Dugout", "Softball", "Scrum Cap",
      "Chalk Bag", "Fins", "Paddle Boat", "Dragon Boat", "Target Ring", "Bowling Shoes", "Cue Ball", "Eight Ball",
      "Puzzle Box", "Bingo Card", "Lottery Ball", "Botanist", "Chemist", "Animator", "Midwife", "Janitor",
      "Gardener", "Rancher", "Shepherd", "Milkman", "Butcher", "Florist", "Cashier", "Potter",
      "Weaver", "Carver", "Editor", "Tourist", "Traveler", "Sherpa", "Diver", "Courier",
      "Mascot", "Drummer", "Pianist", "Flutist", "Busker", "Acrobat", "Juggler", "Goatherd",
      "Lifeguard Chair", "School Shoes", "Dress Shoes", "Loafers", "Cleats", "Sun Hat", "Bucket Hat", "Turban",
      "Fez Hat", "Pakol Cap", "Prayer Cap", "Scrubs", "Poncho", "Shawl", "Dupatta", "Kurta",
      "Sherwani", "Lehenga", "Hanbok", "Parka", "Cardigan", "Vest", "Swim Cap", "Bandana",
      "Locket", "Bangle", "Tassel", "Fringe", "Sequin", "Button Jar", "Laundry Line", "Rickshaw",
      "Camel Cart", "Horse Cart", "Ox Cart", "Donkey Cart", "Plow", "Cement Truck", "Container Truck", "Flatbed Truck",
      "Refrigerated Truck", "Airport Bus", "Biplane", "Glider", "Seaplane", "Blimp", "Sleeping Car", "Dining Car",
      "Monorail", "Fishing Boat", "Rowboat", "Dinghy", "Canal Boat", "Tugboat", "Barge", "Lifeboat",
      "Rescue Boat", "Airboat", "Car Key", "Roof Rack", "Coolant Bottle", "Tool Cart", "Chainsaw", "Hi Hat",
      "Jukebox", "Songbook", "Choir Book", "Stage Door", "Camera Bag", "Memory Card", "Ink Brush", "Brush Cup",
      "Water Jar", "Paper Boat", "Paper Flower", "Model Car", "Diorama", "Caption Box", "Locked Door", "Plus Sign",
      "Minus Sign", "Equals Sign", "Notification Bell", "Hospital Sign", "Restroom Sign", "Parking Sign"
    ],
    Medium: [
      "Jellyfish", "Crocodile", "Alligator", "Chameleon", "Flamingo", "Ostrich", "Woodpecker", "Hummingbird",
      "Guinea Pig", "Hedgehog", "Raccoon", "Skunk", "Beaver", "Otter", "Polar Bear", "Grizzly Bear",
      "Bison", "Buffalo", "Hyena", "Meerkat", "Mongoose", "Armadillo", "Platypus", "Wombat",
      "Walrus", "Sea Lion", "Manatee", "Narwhal", "Orca", "Stingray", "Swordfish", "Clownfish",
      "Pufferfish", "Piranha", "Sea Urchin", "Scorpion", "Centipede", "Millipede", "Stick Insect", "Cockroach",
      "Tarantula", "Cuttlefish", "Komodo Dragon", "Iguana", "Salamander", "Albatross", "Vulture", "Blue Jay",
      "Kingfisher", "Pheasant", "Falcon", "Condor", "Kiwi Bird", "Griffin", "Mermaid", "Yeti",
      "Capybara", "Porcupine", "Chinchilla", "Peacock Feather", "Fried Chicken", "Spring Roll", "Onion Rings", "Gingerbread Man",
      "Marshmallow", "Club Sandwich", "Quesadilla", "Kiwi Fruit", "Pomegranate", "Asparagus", "Pea Pod", "Artichoke",
      "Zucchini", "Falooda", "Gulab Jamun", "Jalebi", "Sushi Roll", "Candy Shop", "Vending Machine", "Buffet",
      "Dart Board", "Poker Chip", "Rubiks Cube", "Rollerblades", "Ice Skates", "Badminton Racket", "Shuttlecock", "Trampoline",
      "Hula Hoop", "Treadmill", "Exercise Bike", "Gold Medal", "Championship Belt", "Scoreboard", "Stopwatch", "Referee",
      "Umpire", "Starting Blocks", "Marathon Runner", "Surfing Wave", "Rock Climbing", "Climbing Wall", "Archery Target", "Hockey Rink",
      "Figure Skating", "Gymnastics Ring", "Balance Beam", "Trapeze", "Pom Poms", "Marching Band", "Chess King", "Chess Queen",
      "Arcade Machine", "Pinball Machine", "Crossword", "Olympic Torch", "Olympic Rings", "Sports Jersey", "Shin Guards", "Knee Pads",
      "Elbow Pads", "Wrist Guards", "Mouth Guard", "Soccer Cleats", "Karate Gi", "Fencing Mask", "Shot Put", "Pole Vault",
      "Relay Baton", "Kabaddi", "Squash Racket", "Carrom Board", "Ludo Board", "Polo Match", "Camel Race", "Tent Pegging",
      "Rain Cloud", "Constellation", "Tsunami", "Sand Castle", "Tundra", "Prairie", "Mangrove", "Dew Drop",
      "Sandstorm", "Whale Tail", "Binoculars", "Telescope", "Microscope", "Light Switch", "Clothesline", "Clothespin",
      "Feather Duster", "Door Knocker", "Attic Ladder", "Mailbox Flag", "Porch Swing", "Backyard Fence", "Outdoor Grill", "Pool Float",
      "Ceiling Fan", "Chandelier", "String Lights", "Recliner", "Footstool", "Ottoman", "Bar Stool", "Umbrella Stand",
      "Plunger", "Bathroom Scale", "Tape Measure", "Level Tool", "Power Drill", "Pruning Shears", "Hot Balloon", "Cruise Ship",
      "Cargo Ship", "Ambulance", "Limousine", "Crane Machine", "Snowplow", "Double-Decker", "Gondola", "Toll Booth",
      "Control Tower", "Roundabout", "Overpass", "Train Tunnel", "Harbor Dock", "Cargo Container", "Ship Mast", "Businessman",
      "Businesswoman", "Gentleman", "Secretary", "Receptionist", "News Anchor", "Babysitter",
      "Ranch House", "Synagogue", "Stethoscope", "Lunch Tray", "Protractor", "Compass Math", "Periodic Table", "Bunsen Burner",
      "Chalkboard Eraser", "Cafeteria Tray", "Spelling Bee", "Science Project", "Robot Project", "Filing Cabinet", "Whiteboard Marker", "Briefcase",
      "Clipboard", "Spreadsheet", "Pie Chart", "Presentation Slide", "Mic Stand", "Orchestra", "Turntable", "Vinyl Record",
      "Cassette Tape", "Ukulele", "Banjo", "Bagpipes", "Tuning Fork", "Metronome", "Amplifier", "Marionette",
      "Spotlight", "Clapboard", "Ticket Stub", "Graffiti Wall", "Mistletoe", "Piñata",
      "Carnival Mask", "Parade Float", "Lantern Festival", "Cartwheel", "Somersault", "Handstand", "Yoga Pose", "Meditating",
      "Blowing Bubbles", "Skydiving", "Bungee Jump", "Snowboarding", "Ice Skating", "Tying Shoelaces", "Combing Hair", "Piggyback",
      "Trampoline Jump", "Snorkeling", "Scuba Diving", "Zip Lining", "Parachuting", "Hang Gliding", "Sleigh Riding", "Stormy Night",
      "Cyborg", "Crystal Ball", "Potion", "Floating Island", "Portal Door", "Shipwreck", "Fire Extinguisher", "Garden Gnome",
      "Wheelbarrow", "Fence Post", "Mailbox Post", "Makeup Kit", "Ferris Wheel", "Roller Coaster", "Trapeze Artist",
      "Whack-A-Mole", "Stag Beetle", "Boa Constrictor", "Rattlesnake", "Gila Monster", "Monitor Lizard",
      "Flip Flops", "Cufflinks", "Castle Tower", "Drawbridge", "Watchtower", "Greenhouse", "Department Store", "Drive-In Theater",
      "Stadium Lights", "Amphitheater", "Bandstand", "Picnic Shelter", "Courthouse", "Hotel Lobby", "Ferry Terminal", "Border Checkpoint",
      "Smartwatch", "Wifi Router", "Bluetooth Speaker", "Vr Headset", "Streaming Device", "Car Charger", "Robot Vacuum", "3D Printer",
      "Barcode Scanner", "Qr Code", "Gps Device", "Satellite Dish", "Circuit Board", "Usb Drive", "France Map", "Italy Map",
      "Spain Map", "Japan Flag", "China Flag", "India Flag", "Brazil Flag", "Canada Flag", "Australia Flag", "Mexico Flag",
      "Russia Flag", "Uk Flag", "Usa Flag", "South Korea", "Greece Flag", "Turkey Flag", "Netherlands Flag", "Switzerland Flag",
      "Sweden Flag", "Norway Flag", "Argentina Flag", "South Africa", "Kenya Flag", "Thailand Flag", "Vietnam Flag", "Indonesia Flag",
      "Philippines Flag", "New Zealand", "Continent Map", "Tropical Island", "Mountain Range", "Peninsula", "Archipelago", "Volcano Island",
      "Glacier Field", "Delta River", "Surprised Face", "Scared Face", "Confused Face", "Sleepy Face", "Excited Face", "Question Mark",
      "Puzzle Piece", "Traffic Jam", "Construction Zone", "Recycle Symbol", "Handshake", "Contract Signing", "Diploma Roll", "Award Ribbon",
      "Medal Ceremony", "Flamenco Dancer", "Ballet Dancer", "Tap Dance", "Breakdancer", "Salsa Dancers", "Tango Dancers", "Hula Dancer",
      "Lei Necklace", "Totem Pole", "Dreamcatcher", "Viking Helmet", "Roman Toga", "Greek Column", "Hieroglyphics", "Dragon Dance",
      "Torii Gate", "Tribal Mask", "Headdress", "Surprise Party", "Confetti Cannon", "Party Favors", "Balloon Arch", "Wedding Bouquet",
      "Wedding Arch", "Flower Girl", "Ring Bearer", "Best Man", "Wedding Rings", "Bridal Veil", "Baby Mobile", "Baby Rattle",
      "Corn Maze", "Apple Orchard", "Pumpkin Patch", "Cider Mug", "Maple Syrup", "Snow Fort", "Snowball Fight", "Ice Fishing",
      "Ice Sculpture", "Snow Angel", "Ski Lift", "Ski Lodge", "Hot Cocoa", "Summer Camp", "Marshmallow Roast", "Tent Pitching",
      "Trail Map", "Water Canteen", "Hiking Boots", "Beach Volleyball", "Surf Shop", "Sand Dollar", "Lifeguard Tower", "Boardwalk",
      "Fishing Pier", "Scarecrow Contest", "Chicken Coop", "Cow Pasture", "Dairy Farm", "Apple Picking", "Bookstore", "Graphic Novel",
      "Desert Camel", "River Raft", "Waterfall Mist", "Stalactite", "Stalagmite", "Mine Shaft", "Gold Mine", "Diamond Mine",
      "Coal Mine", "Oil Rig", "Grain Elevator", "Cargo Pallet", "Conveyor Belt", "Robot Arm", "Smokestack", "Jacket Zipper",
      "Locker Room", "Protein Shake", "Sweatband", "Headband Sport", "Ankle Brace", "Knee Brace", "Compression Sleeve", "Sports Tape",
      "Whistle Coach", "Clipboard Coach", "Timeout Signal", "Huddle Team", "High-Five", "Fist Pump", "Podium Finish", "Silver Medal",
      "Bronze Medal", "Ribbon Prize", "Certificate Award", "Scoreboard Digital", "Bleachers", "Grandstand", "Ticket Booth", "Turnstile",
      "Vip Seats", "Drive Lane", "Helmet Bike", "Kickstand", "Handlebar", "Jumper Cables", "Engine Block", "Exhaust Pipe",
      "Speedometer", "Dashboard", "Sun Visor", "Rear View", "Gear Shift", "Parking Brake", "Headlight", "Taillight",
      "Windshield", "Car Jack", "Lug Wrench", "Air Filter", "Spark Plug", "Battery Cable", "Motorbike Helmet", "Motorbike Seat",
      "Motorbike Mirror", "Motorbike Exhaust", "Scooter Wheel", "Scooter Seat", "Bicycle Lock", "Kitchen Cabinet", "Kitchen Island", "Kitchen Scale",
      "Timer Kitchen", "Apron Pocket", "Chopstick Rest", "Ginger Slice", "Tofu Block", "Dumpling Steamer", "Pressure Cooker", "Espresso Machine",
      "French Press", "Pour Over", "Coffee Filter", "Tea Infuser", "Ice Bucket", "Cream Pitcher", "Cheese Board", "Pantry Shelf",
      "Freezer Drawer", "Fridge Handle", "Range Hood", "Chair Wheel", "Hole Punch", "Paper Shredder", "Cork Board", "Sticky Tape",
      "Keyboard Tray", "Monitor Stand", "Webcam Clip", "Conference Phone", "Projector Screen", "Flip Chart", "Easel Pad", "Sticky Notes",
      "Scissors Office", "Stamp Pad", "Ink Pad", "Fax Machine", "Photocopier", "Scanner Machine", "Shredder Bin", "Recycle Bin",
      "Office Trash", "Whiteboard Wall", "Reception Desk", "Escalator", "Stairwell", "Garden Trellis", "Garden Arbor", "Garden Lattice",
      "Flower Garland", "Watering Trough", "Sprinkler", "Weeder Tool", "Wheelbarrow Tire", "Mulch Pile", "Cold Frame", "Raised Bed",
      "Hedge Trimmer", "Ivy Vine", "Reed Plant", "Willow Branch", "Toadstool", "Trail Marker", "Carabiner", "Rain Fly",
      "Backpack Frame", "Multi Tool", "Whistle Survival", "Acrylic Paint", "Oil Paint", "Craft Glue", "Pom Pom", "Embroidery Hoop",
      "Cross Stitch", "Pottery Kiln", "Ice Chisel", "Weaving Shuttle", "Spinning Wheel", "Tie Dye", "Print Press", "Calligraphy Pen",
      "Parchment", "Wax Seal", "Letter Seal", "Vintage Typewriter", "Cassette Player", "Film Projector", "Slide Projector", "Wedding Invitation",
      "Save-The-Date", "Ribbon Spool", "Bow Gift", "Avalanche", "Thermal Socks", "Frosted Glass", "Fireplace Mantel", "Incense Holder",
      "Asphalt Paver", "Wheelbarrow Construction", "Scaffolding", "Crane Construction", "Ear Protection", "Level Bubble", "Plumb Bob", "Vice Grip",
      "Bolt Cutter", "Wire Cutter", "Pliers Needle", "Socket Wrench", "Caulk Gun", "Natural Bridge", "Timberline", "Desert Plateau",
      "Coastal Plain", "Relief Map", "Compass Rose", "Map Legend",
      "Map Scale", "World Atlas", "Country Border", "Coastline", "Shoreline", "Harbor Bay", "Natural Harbor", "Canal Lock",
      "Reservoir", "Waterfall Plunge Pool", "Rapids Bend", "Ocean Horizon", "Town Hall", "Courtyard", "Public Square", "Market Square",
      "Clock Tower", "Bell Tower", "Waterfront", "Promenade", "Warehouse", "Botanical Garden", "Public Garden", "Memorial Park",
      "Cemetery Gate", "Statue Pedestal", "Fountain Statue", "City Wall", "City Gate", "Watch Post", "Guard Tower", "Signal Tower",
      "Cathedral", "Monastery", "Palace Gate", "Royal Garden", "Fort Gate", "Parade Ground", "Assembly Hall", "Police Booth",
      "Toll Plaza", "Customs Office", "Passport Control", "Train Platform", "Metro Station", "Ticket Counter", "Bus Terminal", "Tram Stop",
      "Taxi Rank", "Bike Station", "Parking Meter", "Parking Ticket", "Pedestrian Bridge", "Sky Bridge", "Underpass", "Zebra Crossing",
      "Traffic Island", "Median Strip", "Street Corner", "Roundabout Sign", "Rail Crossing", "Suspension Bridge", "Arch Bridge", "Covered Bridge",
      "Rail Bridge", "Storm Drain", "Telephone Pole", "Electric Pole", "Charging Station", "Bus Depot", "Rail Yard", "Container Port",
      "Customs Warehouse", "Grain Silo", "Cold Storage", "Fire Watchtower", "Lookout Tower", "Ski Resort", "Beach Resort", "Campground",
      "Caravan Park", "Hostel Dorm", "Guest House", "Tea House", "Restaurant Booth", "Market Stall", "Street Vendor", "Fish Market",
      "Flower Market", "Farmers Market", "Bazaar Stall", "Souvenir Shop", "Emergency Room", "Operating Room", "Veterinary Clinic", "Animal Shelter",
      "Pet Shop", "Barber Pole", "Laundromat", "Dry Cleaner", "Tailor Shop", "Shoe Repair", "Watch Shop", "Jewelry Store",
      "Toy Store", "Music Store", "Camera Shop", "Hardware Store", "Furniture Store", "Plant Nursery", "Florist Shop", "Butcher Shop",
      "Fishmonger", "Greengrocer", "Fruit Stand", "Book Stall", "Newsstand", "Printing Press", "Radio Station", "Tv Studio",
      "Recording Studio", "Sound Booth", "Dance Studio", "Yoga Studio", "Gymnasium", "Martial Arts Dojo", "Skating Rink", "Bowling Alley",
      "Theme Park Gate", "Water Park", "Aquarium Tunnel", "Zoo Enclosure", "Reptile House", "Butterfly House", "Insectarium", "Science Museum",
      "History Museum", "Art Museum", "Children Museum", "Archives Room", "Reading Room", "Lecture Hall", "Auditorium", "School Hallway",
      "School Bus Stop", "Playground Gate", "Sports Complex", "Cricket Ground", "Football Stadium", "Race Track", "Horse Stable", "Riding Arena",
      "Barn Loft", "Farmhouse Porch", "Orchard Rows", "Vineyard Rows", "Olive Grove", "Tea Plantation", "Coffee Plantation", "Rubber Plantation",
      "Sugarcane Field", "Cotton Field", "Wheat Field", "Rice Paddy", "Cornfield", "Vegetable Patch", "Irrigation Canal", "Well House",
      "Village Well", "Hand Pump", "Watermill", "Flour Mill", "Windmill Blades", "Lighthouse Beam", "Harbor Crane", "Door Frame",
      "Window Frame", "Courtyard Fountain", "Lobby Desk", "Ceiling Beam", "Wooden Beam", "Stone Wall", "Brick Wall", "Glass Wall",
      "Curtain Wall", "Tile Roof", "Thatched Roof", "Metal Roof", "Green Roof", "Chimney Pot", "Roof Gutter", "Downspout",
      "Stained Glass Window", "Garage Ramp", "Elevator Shaft", "Spiral Staircase", "Fire Escape", "Stair Landing", "Newel Post", "Capital Column",
      "Arcade", "Dome Ceiling", "Mosque Dome", "Temple Gate", "Torii Gate Red", "Pagoda Roof", "Mosaic Floor", "Tile Mosaic",
      "Marble Floor", "Cobblestone Street", "Gravel Path", "Wooden Deck", "Stone Steps", "Garden Steps", "Retaining Wall", "Fence Gate",
      "Iron Gate", "Privacy Fence", "Picket Fence", "Barbed Wire Fence", "Chain Link Fence", "Stone Fence", "Hedge Maze", "Garden Arch",
      "Trellis Arch", "Statue Niche", "Wall Mural", "Street Mural", "Shop Awning", "Billboard", "Display Case", "Turning Stile",
      "Security Gate", "Metal Detector", "Reception Counter", "Information Desk", "Service Counter", "Checkout Lane", "Queue Barrier", "Velvet Rope",
      "Public Bench", "Park Bench", "Trash Basket", "Drinking Fountain", "Street Clock", "Public Telephone", "Notice Board", "Community Board",
      "Wooden Spoon", "Mixing Spoon", "Glass Tumbler", "Water Jug", "Vacuum Flask", "Spice Tin", "Lunch Tray Divider", "Tea Tray",
      "Table Runner", "Salt Cellar", "Pepper Mill", "Honey Dipper", "Mortar And Pestle", "Grinding Stone", "Clay Oven", "Bread Basket",
      "Fruit Crate", "Tin Can", "Jam Spoon", "Soap Dispenser", "Toilet Paper Roll", "Laundry Detergent", "Fabric Softener", "Clothes Basket",
      "Ironing Board", "Sewing Needle", "Safety Pin", "Pin Cushion", "Wooden Hanger", "Coat Hanger", "Shoe Horn", "Polish Tin",
      "Umbrella Hook", "Wall Hook", "Coat Peg", "Floor Tile", "Carpet Roll", "Wallpaper Roll", "Paint Roller Tray", "Extension Cord",
      "Power Strip", "Plug Adapter", "Nightstand", "Vanity Mirror", "Jewelry Stand", "Storage Bin", "Packing Tape", "Bubble Wrap",
      "Shipping Label", "Postcard Stamp", "Letterbox", "Desk Drawer", "Desk Calendar", "Rubber Eraser", "Pencil Sharpener", "Fountain Ink",
      "Stamp Album", "Coin Album", "File Stack", "Newspaper Stack", "Library Shelf", "Reading Glasses", "Floor Cushion", "Seat Cushion",
      "Mosquito Net", "Ice Pack Lunch", "Eye Mask", "Ear Plugs", "Boarding Pass", "Luggage Tag", "Travel Adapter", "Money Belt",
      "Camp Mug", "Portable Stove", "Mess Kit", "Survival Kit", "First Aid Kit", "Tool Roll", "Workbench", "Paint Ladder",
      "Dust Mask", "Work Apron", "Measuring Wheel", "Chalk Reel", "Garden Kneeler", "Seed Tray", "Plant Marker", "Plant Label",
      "Rain Barrel", "Bird Seed", "Pet Carrier", "Scratch Post", "Aquarium Net", "Fish Food", "Horse Saddle", "Horseshoe",
      "Horse Bridle", "Chicken Feeder", "Beehive Frame", "Honeycomb Frame", "Fishing Tackle Box", "Bait Bucket", "Camp Cooler", "Thermometer Wall",
      "Barometer", "Hygrometer", "Weather Station", "Air Purifier", "Dehumidifier", "Humidifier", "Heated Mug", "Desk Fan",
      "Box Fan", "Portable Heater", "Space Heater", "Water Heater", "Circuit Breaker", "Door Chain", "Door Latch", "Window Latch",
      "Combination Lock", "Money Clip", "Coin Purse", "Library Pass", "Parking Pass", "Bus Pass", "Raffle Ticket", "Price Sticker",
      "Hand Basket", "Checkout Belt", "Receipt Printer", "Barcode Label", "Inventory Tag", "Name Sticker", "Gift Receipt", "Mangrove Tree",
      "Date Palm", "Coconut Palm", "Grape Vine", "Tea Plant", "Coffee Plant", "Cotton Plant", "Wheat Stalk", "Rice Stalk",
      "Corn Stalk", "Sugarcane", "Water Lily", "Jungle Vine", "Creeper Plant", "Mossy Rock", "Kelp Forest", "Algae Bloom",
      "Fern Frond", "Palm Frond", "Tree Sap", "Flower Bud", "Thorn Bush", "Rose Thorn", "Pine Needle", "Driftwood",
      "Fallen Branch", "Hollow Log", "Bird Feather", "Animal Footprint", "Paw Print", "Hoof Print", "Claw Mark", "Animal Burrow",
      "Fox Den", "Rabbit Hole", "Termite Mound", "Coral Branch", "Coral Polyp", "Tide Pool Crab", "Hermit Crab", "Sea Cucumber",
      "Sea Sponge", "Manta Ray", "Hammerhead Shark", "Blue Whale", "Humpback Whale", "Beluga Whale", "Sperm Whale", "Sea Turtle",
      "Green Turtle", "Loggerhead Turtle", "Angelfish", "Parrotfish", "Pelican Beak", "Eagle Nest", "Owl Nest", "Flamingo Flock",
      "Goose Flock", "Duck Pond", "Rooster Comb", "Turkey Feather", "Peacock Tail", "Camel Hump", "Elephant Trunk", "Rhino Horn",
      "Deer Antlers", "Moose Antlers", "Goat Horns", "Ram Horns", "Cow Udder", "Horse Mane", "Lion Mane", "Tiger Stripes",
      "Zebra Stripes", "Giraffe Spots", "Leopard Spots", "Turtle Shell", "Snail Shell", "Crab Claw", "Lobster Claw", "Scorpion Tail",
      "Bee Swarm", "Ant Colony", "Butterfly Wings", "Dragonfly Wings", "Ladybug Spots", "Praying Mantis", "Dung Beetle", "Leaf Insect",
      "Rain Gauge", "Weather Map", "Weather Balloon", "Storm Cloud", "Shelf Cloud", "Funnel Cloud", "Hailstone", "Snow Drift",
      "Snow Cornice", "Ice Crystals", "Frozen Waterfall", "Frost Pattern", "Dew On Grass", "Rain Puddles", "Muddy Footprints", "Sun Rays",
      "Moon Crater", "Crescent Moon", "Full Moon", "New Moon", "Milky Way", "Star Cluster", "Meteor Crater", "Planet Orbit",
      "Earth Globe", "Magnetic Field", "Northern Lights", "Rainbow Arc", "Double Rainbow", "Heat Wave", "Cold Front", "Warm Front",
      "Wind Sock", "Weather Radar", "Plant Cell", "Animal Cell", "Petri Dish", "Microscope Slide", "Lab Goggles", "Round Bottom Flask",
      "Measuring Cylinder", "Balance Scale", "Digital Scale", "Horseshoe Magnet", "Bar Magnet", "Electric Circuit", "Battery Cell", "Wire Coil",
      "Light Emitting Diode", "Switch Circuit", "Solar Cell", "Sound Wave", "Water Cycle", "Food Chain", "Speed Of Light", "Rocket Launch",
      "Launch Pad", "Mission Control", "Space Capsule", "Space Probe", "Moon Base", "Mars Colony", "Space Telescope", "Comet Tail",
      "Venus Planet", "Mercury Planet", "Earth Orbit", "Solar Eclipse Glasses", "Telescope Lens", "Star Chart", "Set Square", "Triangle Ruler",
      "Graph Paper", "Math Trophy", "Ink Pen", "Lesson Plan", "Homework Sheet", "Exam Paper", "School Timetable", "Class Schedule",
      "School Badge", "Student Desk", "Teacher Desk", "Lab Bench", "Science Fair", "Display Board", "Poster Board", "Report Folder",
      "Book Cover", "Storybook", "Fairy Tale Book", "School Backpack", "Pencil Pouch", "Lunch Pass", "Hall Pass", "Ancient Scroll",
      "Clay Tablet", "Stone Tablet", "Cuneiform Tablet", "Gold Crown", "Royal Scepter", "Royal Throne", "Coat Of Arms", "Family Crest",
      "Heraldic Shield", "Knight Helmet", "Chain Mail", "Suit Of Armor", "Castle Flag", "Peace Flag", "White Flag", "Tribal Drum",
      "Ceremonial Mask", "Festival Mask", "Lion Dance Head", "Dragon Parade", "Paper Lantern", "Sky Lantern", "Rangoli Pattern", "Henna Hand",
      "Mehndi Design", "Prayer Beads", "Rosary Beads", "Prayer Rug", "Calligraphy Scroll", "Incense Burner", "Mosque Lantern", "Oil Diya",
      "Torah Scroll", "Moon And Star", "Yin Yang", "Lotus Symbol", "Scarab Beetle", "Pharaoh Mask", "Totem Mask", "Dream Catcher Hoop",
      "Boomerang", "Didgeridoo", "Kimono Belt", "Samurai Armor", "Viking Ship", "Viking Shield", "Roman Helmet", "Greek Vase",
      "Greek Amphora", "Laurel Wreath", "Olive Wreath", "Olympic Laurel", "Maya Calendar", "Aztec Sun Stone", "Inca Quipu", "Native Canoe",
      "Ger Tent", "Nomad Tent", "Desert Tent", "Market Rug", "Persian Rug", "Turkish Carpet", "Lantern Bazaar", "Spice Bazaar",
      "Silk Road Caravan", "Camel Caravan", "Oasis Tent", "Mining Helmet", "Steam Engine", "Spinning Jenny", "Printing Press Letters", "Quill And Ink",
      "Wax Tablet", "Pocket Watch", "Compass Needle", "Ship Wheel", "Anchor Rope", "Naval Flag", "Treasure Coin", "Ancient Helmet",
      "Museum Artifact", "Fossil Shell", "Dinosaur Bone", "Stone Age Tool", "Arrowhead", "Clay Pot Shard", "Dig Site", "Excavation Trench",
      "Temple Ruins", "Ruined Arch", "Broken Column", "Ancient Amphitheater", "Pita Bread", "Mandi Rice", "Turkish Delight", "Jollof Rice",
      "Suya Skewer", "Bunny Chow", "Quesadilla Stack", "Tres Leches Cake", "Bento Tray", "Banh Mi", "Spring Roll Plate", "Pad Thai",
      "Satay Skewers", "Nasi Goreng", "Dim Sum Basket", "Bao Bun", "Hot Pot", "Peking Duck", "Fortune Cookie", "Tteokbokki",
      "Lassi Glass", "Pani Puri", "Tikka Skewer", "Seekh Kebab", "Chapli Kebab", "Zarda Rice", "Sohan Halwa", "Rooh Afza",
      "Sugarcane Juice", "Coconut Water", "Mint Chutney", "Green Chutney", "Mango Pickle", "Naan Basket", "Tandoori Chicken", "Fish And Chips",
      "Bruschetta", "Gelato Cone", "Fondue Pot", "Pretzel Stand", "Sauerkraut", "Smoked Salmon", "Clam Chowder", "Lobster Roll",
      "Corn Dog", "Apple Cider", "Pumpkin Spice", "Maple Candy", "Trail Mix Bag", "Granola Bar", "Protein Bar", "Fruit Salad",
      "Vegetable Soup", "Lentil Soup", "Bean Stew", "Grilled Corn", "Baked Potato", "Roasted Nuts", "Street Corn", "Snow Cone",
      "Bubble Tea", "Cappuccino", "Latte Art", "Matcha Tea", "Herbal Tea", "Iced Tea", "Mocktail Glass", "Cricket Wicket",
      "Cricket Helmet", "Cricket Stumps", "Cricket Pads", "Football Boot", "Goal Net", "Corner Flag", "Penalty Spot", "Team Bench",
      "Coach Board", "Tactics Board", "Score Sheet", "Line Judge", "Net Post", "Tennis Net", "Table Tennis Paddle", "Ping Pong Net",
      "Basketball Net", "Backboard", "Free Throw Line", "Baseball Diamond", "Pitchers Mound", "Batting Helmet", "Catchers Mask", "Rugby Goalpost",
      "Ice Hockey Mask", "Goalie Mask", "Ice Resurfacer", "Curling Broom", "Ski Goggles", "Snowboard Boots", "Sled Dog", "Dog Sled",
      "Climbing Harness", "Bouldering Wall", "Trail Bike", "Mountain Bike", "Bmx Bike", "Road Bike", "Cycling Jersey", "Water Polo Ball",
      "Swim Lane", "Starting Block", "Lane Rope", "Diving Platform", "Snorkel Mask", "Oxygen Tank", "Surf Wax", "Bodyboard",
      "Wakeboard", "Windsurf Board", "Sailboard", "Rowing Oar", "Archery Bowstring", "Dart Flight", "Dartboard Bullseye", "Bowling Lane",
      "Pool Cue", "Air Hockey Table", "Shuffleboard", "Cornhole Board", "Bean Bag Toss", "Horseshoe Game", "Ring Toss Peg", "Croquet Mallet",
      "Croquet Hoop", "Mini Golf Windmill", "Go Kart Helmet", "Race Flag", "Checkered Flag", "Pit Stop", "Racing Helmet", "Motocross Bike",
      "Skate Ramp", "Half Pipe", "Roller Derby", "Dance Floor", "Karaoke Machine", "Karaoke Mic", "Campfire Songs", "Jigsaw Puzzle",
      "Chess Knight", "Chess Rook", "Chess Bishop", "Chess Pawn", "Go Board", "Card Deck", "Card House", "Magic Cards",
      "Role Playing Dice", "Miniature Figure", "Game Board Path", "Token Piece", "Spinner Wheel", "Archaeologist", "Geologist", "Cartographer",
      "Meteorologist", "Marine Biologist", "Physicist", "Mathematician", "Programmer", "Web Designer", "Game Developer", "Data Analyst",
      "Lab Technician", "Paramedic", "Pharmacist", "Optometrist", "Radiologist", "Nutritionist", "Housekeeper", "Groundskeeper",
      "Landscaper", "Beekeeper", "Shopkeeper", "Tailor Apprentice", "Shoemaker", "Watchmaker", "Blacksmith", "Glassblower",
      "Calligrapher", "Publisher", "Translator", "Interpreter", "Archivist", "Museum Curator", "Historian", "Backpacker",
      "Mountaineer", "Safari Guide", "Sailor Captain", "Harbor Master", "Train Driver", "Bus Driver", "Taxi Driver", "Rickshaw Driver",
      "Delivery Rider", "Traffic Warden", "Parking Attendant", "Flight Mechanic", "Air Traffic Controller", "Ship Engineer", "Railway Guard", "Ticket Inspector",
      "Cinema Usher", "Stage Manager", "Makeup Artist", "Costume Designer", "Set Designer", "Sound Engineer", "Camera Operator", "Film Director",
      "Film Producer", "Radio Host", "Podcaster", "News Reporter", "Weather Reporter", "Sports Commentator", "Referee Assistant", "Ball Boy",
      "Cheerleader", "Violinist", "Trumpeter", "Conductor", "Choir Singer", "Street Musician", "Storyteller", "Puppeteer",
      "Ringmaster", "Lion Tamer", "Snake Charmer", "Camel Rider", "Horse Rider", "Village Elder", "Market Vendor", "Street Artist",
      "Graffiti Artist", "Park Ranger Hut", "Forest Ranger", "Beach Lifeguard", "Ski Instructor", "Swim Coach", "Yoga Student", "Meditation Teacher",
      "Language Teacher", "Math Teacher", "Science Teacher", "Art Teacher", "Music Teacher", "School Principal", "School Monitor", "Crossing Patrol",
      "Lunch Lady", "Cafeteria Worker", "Librarian Desk", "Book Collector", "Coin Collector", "Stamp Collector", "Bird Watcher", "Stargazer",
      "Cloud Watcher", "Photobomber", "Tour Group", "Marching Drummer", "Flag Bearer", "Bridesmaid", "Groomsman", "Flower Seller",
      "Ice Cream Seller", "Balloon Seller", "Toy Maker", "Kite Maker", "Basket Weaver", "Rug Maker", "Rain Boots", "Work Boots",
      "Football Cleats", "Shin Pad", "Wrist Band", "Sports Visor", "Helmet Visor", "Face Shield", "Surgical Mask", "Apron Strings",
      "Chef Apron", "School Uniform", "Sports Uniform", "Lab Uniform", "Safety Vest Orange", "Life Vest Jacket", "Sari Border", "Shalwar Kameez",
      "Waistcoat", "Kimono Sleeve", "Cheongsam", "Poncho Cloak", "Cape Cloak", "Rain Poncho", "Wool Coat", "Trench Coat",
      "Puffer Jacket", "Denim Jacket", "Leather Jacket", "Varsity Jacket", "Polo Shirt", "Baseball Jersey", "Football Jersey", "Cricket Jersey",
      "Tracksuit", "Track Pants", "Gym Shorts", "Yoga Pants", "Goggles Strap", "Wedding Veil", "Flower Crown Veil", "Hair Scarf",
      "Handkerchief", "Pocket Square", "Tie Clip", "Lapel Pin", "Watch Strap", "Fitness Band", "Charm Necklace", "Ankle Bracelet",
      "Jewelry Clasp", "Fabric Roll", "Silk Cloth", "Cotton Cloth", "Wool Yarn", "Linen Cloth", "Denim Fabric", "Velvet Cloth",
      "Lace Ribbon", "Embroidery Thread", "Zipper Pull", "Clothes Pin", "Tailor Chalk", "Dress Form", "Mannequin", "Auto Rickshaw",
      "Cycle Rickshaw", "Tractor Trailer", "Harvester", "Seed Drill", "Water Tanker", "Fuel Tanker", "Mobile Crane", "Tower Crane",
      "Street Sweeper", "Forklift Forks", "Warehouse Trolley", "Shopping Trolley", "Airport Shuttle", "Jet Bridge", "Boarding Stairs", "Fuel Truck Airport",
      "Baggage Belt", "Cargo Plane", "Paraglider", "Hang Glider", "Rescue Helicopter", "News Helicopter", "Crop Duster", "Private Jet",
      "Train Engine", "Steam Locomotive", "Diesel Locomotive", "Electric Locomotive", "Freight Train", "Cargo Wagon", "Passenger Carriage", "Tram Cable",
      "Chairlift", "Ski Gondola", "Houseboat", "Oil Tanker", "Research Vessel", "Water Taxi", "Jet Ski", "Car Ferry",
      "Anchor Chain", "Boat Oar", "Boat Rudder", "Sail Mast", "Ship Sail", "Motorboat Engine", "Train Whistle", "Train Signal",
      "Rail Switch", "Railway Crossing Gate", "Traffic Camera", "Speed Camera", "Parking Sensor", "Ev Charger", "Charging Cable", "Car Remote",
      "Dashboard Camera", "Rear Camera", "Bike Carrier", "Child Car Seat", "Baby Car Seat", "Car Seat Cover", "Floor Mats", "Windshield Washer",
      "Engine Oil", "Tire Pump", "Air Compressor", "Generator", "Portable Generator", "Water Pump", "Pressure Washer", "Leaf Blower",
      "Hedge Cutter", "Sewing Motor", "Printing Machine", "Coin Machine", "Ticket Machine", "Vending Slot", "Concert Stage", "Concert Ticket",
      "Music Festival", "Festival Wristband", "Stage Speaker", "Subwoofer", "Mixing Console", "Audio Mixer", "Soundboard", "Equalizer",
      "Studio Headphones", "Pop Filter", "Recording Mic", "Podcast Mic", "Boom Stand", "Guitar Pick", "Guitar Strap", "Violin Bow",
      "Cello Bow", "Piano Keys", "Keyboard Stand", "Drum Pedal", "Snare Drum", "Bass Drum", "Tom Drum", "Ride Cymbal",
      "Music Album", "Album Cover", "Record Sleeve", "Sheet Stand", "Opera Glasses", "Theater Mask", "Comedy Mask", "Tragedy Mask",
      "Stage Prop", "Set Piece", "Orchestra Pit", "Ticket Queue", "Box Office", "Balcony Seat", "Aisle Seat", "Cinema Projector",
      "Movie Reel Can", "Film Strip", "Green Screen", "Clapper Board", "Storyboard", "Camera Lens", "Zoom Lens", "Tripod Head",
      "Photo Frame Wall", "Paint Tube", "Paint Scraper", "Canvas Frame", "Wooden Easel", "Palette Knife", "Calligraphy Brush", "Color Wheel",
      "Art Mannequin", "Life Drawing", "Plaster Statue", "Charcoal Drawing", "Paper Roll", "Craft Paper", "Colored Paper", "Cardstock",
      "Paper Cutter", "Hole Puncher", "Hot Glue", "Craft Sticks", "Pipe Cleaners", "Beads Tray", "Origami Paper", "Paper Crane",
      "Puppet Stage", "Shadow Puppet", "Hand Puppet", "Sock Puppet", "Doll Clothes", "Model Airplane", "Model Train", "Miniature House",
      "Comic Panel", "Speech Bubble", "Thought Bubble", "Newspaper Comic", "Cartoon Face", "Animation Frame", "Idea Bulb", "Teamwork Puzzle",
      "Growth Chart", "Target Goal", "Finish Flag", "Mountain Challenge", "Key To Success", "Broken Chain", "Chain Link", "Heart Pulse",
      "Peace Symbol", "Warning Triangle", "Information Icon", "Help Button", "Question Bubble", "Exclamation Mark", "Check Mark", "Cross Mark",
      "Wifi Symbol", "Battery Icon", "Download Arrow", "Upload Arrow", "Play Button", "Pause Button", "Stop Button", "Rewind Button",
      "Fast Forward Button", "Mute Icon", "Volume Icon", "Search Icon", "Home Icon", "Settings Gear", "Trash Icon", "Save Icon",
      "Folder Icon", "Calendar Icon", "Location Pin", "Map Pin", "Navigation Arrow", "Compass Arrow", "North Arrow", "Recycle Arrows",
      "Green Energy", "Water Drop Icon", "Fire Icon", "Leaf Icon", "Sun Icon", "Moon Icon", "Star Icon", "Medal Icon",
      "Ribbon Icon", "Fragile Sticker", "This Side Up", "Exit Arrow", "No Entry Sign", "One Way Sign", "Speed Limit Sign", "School Crossing Sign",
      "Elevator Icon", "Stairs Icon", "Wheelchair Symbol", "Baby Changing Sign", "Bus Icon", "Train Icon", "Airplane Icon", "Ship Icon",
      "Bicycle Icon", "Walking Icon"
    ],
    Hard: [
      "Frankenstein", "Dracula", "Vampire", "Werewolf", "Zombie", "Julius Caesar", "Cleopatra", "Mona Lisa",
      "Einstein", "Isaac Newton", "Charles Darwin", "Shakespeare", "Abraham Lincoln", "George Washington", "Columbus", "Amelia Earhart",
      "Neil Armstrong", "Mahatma Gandhi", "Mother Teresa", "Nelson Mandela", "Thomas Edison", "Alexander Bell", "Marie Curie", "Nikola Tesla",
      "Ben Franklin", "Queen Elizabeth", "Napoleon", "Leprechaun", "Centaur", "Minotaur", "Phoenix", "Medusa",
      "Poseidon", "Hades", "Athena", "Apollo", "Cupid", "Eiffel Tower", "Statue Liberty", "Big Ben",
      "Leaning Tower", "Colosseum", "Taj Mahal", "Great Wall", "Pyramids", "Sphinx Statue", "Stonehenge", "Mount Rushmore",
      "Golden Gate", "Sydney Opera", "Burj Khalifa", "Empire State", "Christ Redeemer", "Machu Picchu", "Niagara Falls", "Grand Canyon",
      "Mount Everest", "Mount Fuji", "Barrier Reef", "Amazon Rainforest", "Sahara Desert", "North Pole", "South Pole", "Loch Ness",
      "Venice Canal", "Times Square", "Hollywood Sign", "London Eye", "Tower Bridge", "Buckingham Palace", "White House", "Capitol Building",
      "Brooklyn Bridge", "Space Needle", "Alcatraz", "Disneyland Castle", "Vegas Strip", "Kremlin", "Red Square", "Acropolis",
      "Parthenon", "Petra", "Angkor Wat", "Forbidden City", "Kilimanjaro", "Victoria Falls", "Badshahi Mosque", "Faisal Mosque",
      "Lahore Fort", "Trick-Or-Treat Bag", "Cupid Arrow", "Jack-In-The-Box", "Odometer", "Clutch Pedal", "Radiator", "Timing Belt",
      "Alternator", "Macrame", "Dye Vat", "Silk Screen", "Linocut", "Etching Tool", "Engraving Tool", "Curling Stone",
      "Intertidal Zone", "Shingle Beach", "Glacial Valley", "U Shaped Valley", "V Shaped Valley", "Trade Winds", "Rain Shadow", "Aurora Borealis",
      "Aurora Australis", "Latitude Line", "Longitude Line", "Hemisphere", "Topographic Map", "Contour Line", "Dam Spillway", "Dry Dock",
      "Shipyard", "Refinery", "Foundry", "Observatory", "Planetarium", "Mausoleum", "Obelisk", "Triumphal Arch",
      "Minaret", "Steeple", "Spire", "Gurdwara", "Battlements", "Rampart", "Bunker", "Watch Bunker",
      "Barracks", "Embassy", "Consulate", "Parliament House", "Supreme Court", "Immigration Desk", "Cul De Sac", "Boulevard",
      "Aqueduct", "Viaduct", "Pipeline", "Water Pipeline", "Sewer Grate", "Manhole Cover", "Transmission Tower", "Substation",
      "Atrium", "Foyer", "Pediment", "Colonnade", "Buttress", "Flying Buttress", "Vaulted Ceiling", "Cupola",
      "Minaret Balcony", "Keystone", "Dna Helix", "Cell Membrane", "Bacteria", "Virus Shape", "Pipette", "Graduated Cylinder",
      "Erlenmeyer Flask", "Laser Beam", "Carbon Cycle", "Ecosystem Web", "Voltage Meter", "Lunar Rover", "Satellite Orbit", "Radio Telescope",
      "Observatory Dome", "Asteroid Belt", "Dwarf Planet", "Lunar Eclipse", "Zodiac Wheel", "Coordinate Plane", "Venn Diagram", "Equation Board",
      "Library Catalogue", "Card Catalogue", "Pickleball Paddle", "Pickleball", "Racquetball", "Belay Device", "Quiver", "Foosball Table",
      "Mahjong Tiles", "Backgammon Board", "Scrabble Tiles", "Physiotherapist", "Combine Harvester", "Concrete Pump", "Road Grader", "Steamroller",
      "Excavator Bucket", "Pallet Jack", "Airport Tug", "Baggage Carousel", "Airship", "Parachute Canopy", "Maglev Train", "Funicular",
      "Hovercraft", "Ship Propeller", "Ship Wheelhouse", "Darkroom", "Photo Enlarger", "Brainstorm Cloud", "Road To Success", "Balance Scale Justice",
      "Open Door Opportunity", "Infinity Sign", "Percent Sign", "Hashtag", "At Symbol", "Loading Wheel", "Cloud Upload", "Cloud Download",
      "Carbon Footprint", "Certificate Seal", "Approved Stamp"
    ]
  },
  "Movies & Shows": {
    Easy: [
      "Batman", "Shark", "Pirate", "Wizard", "Robot", "Ghost", "Alien", "Dragon"
    ],
    Medium: [
      "Superhero landing", "Plot twist", "Cliffhanger", "Movie marathon", "Red carpet", "Sequel", "Soundtrack", "Cameo"
    ],
    Hard: [
      "Post-credits scene", "Unreliable narrator", "Found footage", "Slow-motion explosion", "Fourth wall break", "Anti-hero"
    ]
  },
  "Food & Drink": {
    Easy: [
      "Pizza", "Burger", "Taco", "Donut", "Cookie", "Noodles", "Pancake", "Cheese"
    ],
    Medium: [
      "Street food", "Food truck", "Buffet", "Smoothie bowl", "Barbecue", "Dim sum", "Hot pot", "Espresso"
    ],
    Hard: [
      "Molecular gastronomy", "Farm to table", "Fermented tea", "Tasting menu", "Food coma"
    ]
  },
  "Tech & Internet": {
    Easy: [
      "Laptop", "Wifi", "Mouse", "Robot", "Drone", "Battery", "Headphones", "Charger"
    ],
    Medium: [
      "Video call", "Firewall", "Server room", "Touchscreen", "Smartwatch", "Livestream", "Algorithm", "Chatbot"
    ],
    Hard: [
      "Artificial intelligence", "Blockchain", "Augmented reality", "Quantum bit", "Neural network", "Data breach"
    ]
  }
};

export function pickWord(packName, difficulty, excludeList = []) {
  const pack = WORD_PACKS[packName] || WORD_PACKS.Classic;
  const list = pack[difficulty] || pack.Medium;
  const available = list.filter((word) => !excludeList.includes(word));
  const pool = available.length ? available : list;
  return pool[Math.floor(Math.random() * pool.length)];
}

export function pickWordChoices(packName, difficulty, excludeList = [], count = 3) {
  const pack = WORD_PACKS[packName] || WORD_PACKS.Classic;
  const list = pack[difficulty] || pack.Medium;
  const available = list.filter((word) => !excludeList.includes(word));
  const pool = available.length >= count ? available : list;
  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}
